/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type IssueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "issue";
};

export type StandaloneBookReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "standaloneBook";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?:
        | "normal"
        | "normal-center"
        | "normal-right"
        | "h2"
        | "h3"
        | "h4"
        | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href: string;
            _type: "link";
            _key: string;
          }
        | {
            reference:
              | ArticleReference
              | IssueReference
              | StandaloneBookReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | {
      hasHeader?: boolean;
      title?: string;
      table?: Table;
      _type: "customTable";
      _key: string;
    }
  | {
      style?: "default" | "dashed";
      _type: "divider";
      _key: string;
    }
>;

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  content?: RichText;
};

export type SearchPage = {
  _id: string;
  _type: "searchPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  queryLabel?: string;
  queryPlaceholder?: string;
  authorLabel?: string;
  authorAllOption?: string;
  issueLabel?: string;
  issueAllOption?: string;
  tagLabel?: string;
  tagSearchPlaceholder?: string;
  resetButtonLabel?: string;
  resultsHeading?: string;
  readButtonLabel?: string;
  noResultsTitle?: string;
  noResultsDescription?: string;
};

export type EnglishArticlesPage = {
  _id: string;
  _type: "englishArticlesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  readButtonLabel?: string;
  emptyTitle?: string;
  emptyDescription?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: RichText;
  recipientEmail?: string;
  formNameLabel?: string;
  formNamePlaceholder?: string;
  formEmailLabel?: string;
  formEmailPlaceholder?: string;
  formMessageLabel?: string;
  formMessagePlaceholder?: string;
  formSubmitButtonLabel?: string;
  formSuccessTitle?: string;
  formSuccessMessage?: string;
  formSuccessButtonLabel?: string;
  formErrorMessage?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: RichText;
};

export type MagazinePage = {
  _id: string;
  _type: "magazinePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  carouselSelectLabel?: string;
  articlesTabLabel?: string;
  audiobookTabLabel?: string;
  audiobookUnavailableLabel?: string;
  downloadPdfButtonLabel?: string;
  emptyTitle?: string;
  emptyDescription?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroTitle?: string;
  heroSubtitle?: string;
  latestIssueTitle?: string;
  welcomeTitle?: string;
  welcomeContent?: RichText;
  popularTagsTitle?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtitle?: string;
  scripture?: string;
  slug: Slug;
  author?: AuthorReference;
  language: "hu" | "en";
  translation?: ArticleReference;
  issue?: IssueReference;
  order?: number;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  content: RichText;
  footnotes?: Array<{
    number?: string;
    text?: string;
    anchorId?: string;
    _type: "footnoteItem";
    _key: string;
  }>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type StandaloneBook = {
  _id: string;
  _type: "standaloneBook";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  subtitle?: string;
  youtubeUrl?: string;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  pdfFile: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  content: RichText;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Issue = {
  _id: string;
  _type: "issue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  issueNumber: number;
  issueType: "regular" | "special";
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  youtubeUrl?: string;
  pdfFile: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  publishedAt: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerTitle?: string;
  headerSubtitle?: string;
  headerSearchButtonLabel?: string;
  headerMenu?: Array<{
    label?: string;
    url?: string;
    _type: "menuItem";
    _key: string;
  }>;
  footerCopyright?: string;
  footerQuoteText?: string;
  footerQuoteSource?: string;
  footerMenu1Title?: string;
  footerMenu1?: Array<{
    label?: string;
    url?: string;
    _type: "footerMenuItem";
    _key: string;
  }>;
  footerMenu2Title?: string;
  footerMenu2?: Array<{
    label?: string;
    url?: string;
    _type: "footerMenuItem";
    _key: string;
  }>;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ArticleReference
  | IssueReference
  | StandaloneBookReference
  | SanityImageAssetReference
  | RichText
  | Tag
  | Slug
  | PrivacyPage
  | SearchPage
  | EnglishArticlesPage
  | ContactPage
  | AboutPage
  | MagazinePage
  | HomePage
  | AuthorReference
  | TagReference
  | Article
  | SanityFileAssetReference
  | StandaloneBook
  | Table
  | SanityImageCrop
  | SanityImageHotspot
  | Issue
  | Author
  | SiteSettings
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/queries.ts
// Variable: GET_SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  headerTitle,  headerSubtitle,  headerSearchButtonLabel,  headerMenu[]{    label,    url  },  footerCopyright,  footerQuoteText,  footerQuoteSource,  footerMenu1Title,  footerMenu1[]{    label,    url  },  footerMenu2Title,  footerMenu2[]{    label,    url  }}
export type GET_SITE_SETTINGS_QUERY_RESULT = {
  headerTitle: string | null;
  headerSubtitle: string | null;
  headerSearchButtonLabel: string | null;
  headerMenu: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  footerCopyright: string | null;
  footerQuoteText: string | null;
  footerQuoteSource: string | null;
  footerMenu1Title: string | null;
  footerMenu1: Array<{
    label: string | null;
    url: string | null;
  }> | null;
  footerMenu2Title: string | null;
  footerMenu2: Array<{
    label: string | null;
    url: string | null;
  }> | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{  heroImage {    asset->{      _id,      url    },    alt  },  heroTitle,  heroSubtitle,  latestIssueTitle,  welcomeTitle,  welcomeContent[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          _id,          title,          slug,          issueNumber,          issueType,          publishedAt        }      }    }  },  popularTagsTitle}
export type GET_HOME_PAGE_QUERY_RESULT = {
  heroImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string | null;
  } | null;
  heroTitle: string | null;
  heroSubtitle: string | null;
  latestIssueTitle: string | null;
  welcomeTitle: string | null;
  welcomeContent: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h2"
          | "h3"
          | "h4"
          | "normal-center"
          | "normal-right"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "article";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  }
                | {
                    _type: "issue";
                    _id: string;
                    title: string;
                    slug: null;
                    issueNumber: number;
                    issueType: "regular" | "special";
                    publishedAt: string;
                  }
                | {
                    _type: "standaloneBook";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        hasHeader?: boolean;
        title?: string;
        table?: Table;
        _type: "customTable";
        _key: string;
        markDefs: null;
      }
    | {
        style?: "dashed" | "default";
        _type: "divider";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  popularTagsTitle: string | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_MAGAZINE_PAGE_QUERY
// Query: *[_type == "magazinePage"][0]{  title,  description,  carouselSelectLabel,  articlesTabLabel,  audiobookTabLabel,  audiobookUnavailableLabel,  downloadPdfButtonLabel,  emptyTitle,  emptyDescription}
export type GET_MAGAZINE_PAGE_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  carouselSelectLabel: string | null;
  articlesTabLabel: string | null;
  audiobookTabLabel: string | null;
  audiobookUnavailableLabel: string | null;
  downloadPdfButtonLabel: string | null;
  emptyTitle: string | null;
  emptyDescription: string | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{  _id,  title,  content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          _id,          title,          slug,          issueNumber,          issueType,          publishedAt        }      }    }  }}
export type GET_ABOUT_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h2"
          | "h3"
          | "h4"
          | "normal-center"
          | "normal-right"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "article";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  }
                | {
                    _type: "issue";
                    _id: string;
                    title: string;
                    slug: null;
                    issueNumber: number;
                    issueType: "regular" | "special";
                    publishedAt: string;
                  }
                | {
                    _type: "standaloneBook";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        hasHeader?: boolean;
        title?: string;
        table?: Table;
        _type: "customTable";
        _key: string;
        markDefs: null;
      }
    | {
        style?: "dashed" | "default";
        _type: "divider";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]{  _id,  title,  content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          _id,          title,          slug,          issueNumber,          issueType,          publishedAt        }      }    }  },  recipientEmail,  formNameLabel,  formNamePlaceholder,  formEmailLabel,  formEmailPlaceholder,  formMessageLabel,  formMessagePlaceholder,  formSubmitButtonLabel,  formSuccessTitle,  formSuccessMessage,  formSuccessButtonLabel,  formErrorMessage}
export type GET_CONTACT_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h2"
          | "h3"
          | "h4"
          | "normal-center"
          | "normal-right"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "article";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  }
                | {
                    _type: "issue";
                    _id: string;
                    title: string;
                    slug: null;
                    issueNumber: number;
                    issueType: "regular" | "special";
                    publishedAt: string;
                  }
                | {
                    _type: "standaloneBook";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        hasHeader?: boolean;
        title?: string;
        table?: Table;
        _type: "customTable";
        _key: string;
        markDefs: null;
      }
    | {
        style?: "dashed" | "default";
        _type: "divider";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
  recipientEmail: string | null;
  formNameLabel: string | null;
  formNamePlaceholder: string | null;
  formEmailLabel: string | null;
  formEmailPlaceholder: string | null;
  formMessageLabel: string | null;
  formMessagePlaceholder: string | null;
  formSubmitButtonLabel: string | null;
  formSuccessTitle: string | null;
  formSuccessMessage: string | null;
  formSuccessButtonLabel: string | null;
  formErrorMessage: string | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_ENGLISH_ARTICLES_PAGE_QUERY
// Query: *[_type == "englishArticlesPage"][0]{  title,  description,  readButtonLabel,  emptyTitle,  emptyDescription}
export type GET_ENGLISH_ARTICLES_PAGE_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  readButtonLabel: string | null;
  emptyTitle: string | null;
  emptyDescription: string | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_PRIVACY_PAGE_QUERY
// Query: *[_type == "privacyPage"][0]{  _id,  title,  slug,  content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        "reference": reference->{          _type,          _id,          title,          slug,          issueNumber,          issueType,          publishedAt        }      }    }  }}
export type GET_PRIVACY_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h2"
          | "h3"
          | "h4"
          | "normal-center"
          | "normal-right"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "article";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  }
                | {
                    _type: "issue";
                    _id: string;
                    title: string;
                    slug: null;
                    issueNumber: number;
                    issueType: "regular" | "special";
                    publishedAt: string;
                  }
                | {
                    _type: "standaloneBook";
                    _id: string;
                    title: string;
                    slug: Slug;
                    issueNumber: null;
                    issueType: null;
                    publishedAt: null;
                  };
              _type: "internalLink";
              _key: string;
            }
          | {
              href: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        hasHeader?: boolean;
        title?: string;
        table?: Table;
        _type: "customTable";
        _key: string;
        markDefs: null;
      }
    | {
        style?: "dashed" | "default";
        _type: "divider";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_ENGLISH_ARTICLES_QUERY
// Query: *[_type == "article" && language == "en"] | order(_createdAt desc){  _id,  title,  subtitle,  scripture,  slug,  language,  author->{    _id,    name  },  tags[]->{    _id,    title,    slug  },  "issue": issue->{    _id,    title,    issueNumber,    issueType,    publishedAt  }}
export type GET_ENGLISH_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  subtitle: string | null;
  scripture: string | null;
  slug: Slug;
  language: "en";
  author: {
    _id: string;
    name: string;
  } | null;
  tags: Array<{
    _id: string;
    title: string;
    slug: Slug;
  }> | null;
  issue: {
    _id: string;
    title: string;
    issueNumber: number;
    issueType: "regular" | "special";
    publishedAt: string;
  } | null;
}>;

// Source: ../web/src/lib/queries.ts
// Variable: GET_SEARCH_PAGE_QUERY
// Query: *[_type == "searchPage"][0]{  title,  description,  queryLabel,  queryPlaceholder,  authorLabel,  authorAllOption,  issueLabel,  issueAllOption,  tagLabel,  tagSearchPlaceholder,  resetButtonLabel,  resultsHeading,  readButtonLabel,  noResultsTitle,  noResultsDescription}
export type GET_SEARCH_PAGE_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  queryLabel: string | null;
  queryPlaceholder: string | null;
  authorLabel: string | null;
  authorAllOption: string | null;
  issueLabel: string | null;
  issueAllOption: string | null;
  tagLabel: string | null;
  tagSearchPlaceholder: string | null;
  resetButtonLabel: string | null;
  resultsHeading: string | null;
  readButtonLabel: string | null;
  noResultsTitle: string | null;
  noResultsDescription: string | null;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_NEWEST_ISSUE_QUERY
// Query: *[_type == "issue"] | order(publishedAt desc, issueNumber desc)[0]{    _id,    title,    issueNumber,    issueType,    publishedAt,    youtubeUrl,    "pdfUrl": pdfFile.asset->url,    coverImage {        asset->{            _id,            url        },        alt    },    "articles": *[_type == "article" && issue._ref == ^._id] | order(order asc) {        _id,        title,        subtitle,        scripture,        slug,        language,        author->{            _id,            name        },        tags[]->{            _id,            title,            slug        }    }}
export type GET_NEWEST_ISSUE_QUERY_RESULT = {
  _id: string;
  title: string;
  issueNumber: number;
  issueType: "regular" | "special";
  publishedAt: string;
  youtubeUrl: string | null;
  pdfUrl: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string | null;
  };
  articles: Array<{
    _id: string;
    title: string;
    subtitle: string | null;
    scripture: string | null;
    slug: Slug;
    language: "en" | "hu";
    author: {
      _id: string;
      name: string;
    } | null;
    tags: Array<{
      _id: string;
      title: string;
      slug: Slug;
    }> | null;
  }>;
} | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_ALL_ISSUES_QUERY
// Query: *[_type == "issue"] | order(publishedAt desc, issueNumber desc) {    _id,    title,    issueNumber,    issueType,    publishedAt,    youtubeUrl,    "pdfUrl": pdfFile.asset->url,    coverImage {        asset->{            _id,            url        },        alt    },    "articleCount": count(*[_type == "article" && issue._ref == ^._id]),    "articles": *[_type == "article" && issue._ref == ^._id] | order(order asc) {        _id,        title,        subtitle,        scripture,        slug,        language,        author->{            _id,            name        },        tags[]->{            _id,            title,            slug        }    }}
export type GET_ALL_ISSUES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  issueNumber: number;
  issueType: "regular" | "special";
  publishedAt: string;
  youtubeUrl: string | null;
  pdfUrl: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string | null;
  };
  articleCount: number;
  articles: Array<{
    _id: string;
    title: string;
    subtitle: string | null;
    scripture: string | null;
    slug: Slug;
    language: "en" | "hu";
    author: {
      _id: string;
      name: string;
    } | null;
    tags: Array<{
      _id: string;
      title: string;
      slug: Slug;
    }> | null;
  }>;
}>;

// Source: ../web/src/lib/queries.ts
// Variable: GET_DOCUMENT_BY_SLUG_QUERY
// Query: *[_type in ["article", "standaloneBook"] && slug.current == $slug][0]{    _type,    _id,    title,    subtitle,    scripture,    slug,    language,    coverImage {        asset->{            _id,            url        },        alt    },    youtubeUrl,    "pdfUrl": pdfFile.asset->url,    author->{        _id,        name    },    tags[]->{        _id,        title,        slug    },    footnotes[]{        number,        text,        anchorId    },    "issue": issue->{        _id,        title,        issueNumber,        issueType,        publishedAt,        "articles": *[_type == "article" && issue._ref == ^._id] | order(order asc) {            _id,            title,            slug        }    },    "translation": coalesce(        translation->{            _id,            title,            slug,            language        },        *[_type == "article" && translation._ref == ^._id][0]{            _id,            title,            slug,            language        }    ),    content[]{        ...,        markDefs[]{            ...,            _type == "internalLink" => {                "reference": reference->{                    _type,                    _id,                    title,                    slug,                    issueNumber,                    issueType,                    publishedAt                }            }        }    }}
export type GET_DOCUMENT_BY_SLUG_QUERY_RESULT =
  | {
      _type: "article";
      _id: string;
      title: string;
      subtitle: string | null;
      scripture: string | null;
      slug: Slug;
      language: "en" | "hu";
      coverImage: null;
      youtubeUrl: null;
      pdfUrl: null;
      author: {
        _id: string;
        name: string;
      } | null;
      tags: Array<{
        _id: string;
        title: string;
        slug: Slug;
      }> | null;
      footnotes: Array<{
        number: string | null;
        text: string | null;
        anchorId: string | null;
      }> | null;
      issue: {
        _id: string;
        title: string;
        issueNumber: number;
        issueType: "regular" | "special";
        publishedAt: string;
        articles: Array<{
          _id: string;
          title: string;
          slug: Slug;
        }>;
      } | null;
      translation: {
        _id: string;
        title: string;
        slug: Slug;
        language: "en" | "hu";
      } | null;
      content: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h2"
              | "h3"
              | "h4"
              | "normal-center"
              | "normal-right"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs: Array<
              | {
                  reference:
                    | {
                        _type: "article";
                        _id: string;
                        title: string;
                        slug: Slug;
                        issueNumber: null;
                        issueType: null;
                        publishedAt: null;
                      }
                    | {
                        _type: "issue";
                        _id: string;
                        title: string;
                        slug: null;
                        issueNumber: number;
                        issueType: "regular" | "special";
                        publishedAt: string;
                      }
                    | {
                        _type: "standaloneBook";
                        _id: string;
                        title: string;
                        slug: Slug;
                        issueNumber: null;
                        issueType: null;
                        publishedAt: null;
                      };
                  _type: "internalLink";
                  _key: string;
                }
              | {
                  href: string;
                  _type: "link";
                  _key: string;
                }
            > | null;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            hasHeader?: boolean;
            title?: string;
            table?: Table;
            _type: "customTable";
            _key: string;
            markDefs: null;
          }
        | {
            style?: "dashed" | "default";
            _type: "divider";
            _key: string;
            markDefs: null;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            caption?: string;
            alt?: string;
            _type: "image";
            _key: string;
            markDefs: null;
          }
      >;
    }
  | {
      _type: "standaloneBook";
      _id: string;
      title: string;
      subtitle: string | null;
      scripture: null;
      slug: Slug;
      language: null;
      coverImage: {
        asset: {
          _id: string;
          url: string;
        } | null;
        alt: string | null;
      };
      youtubeUrl: string | null;
      pdfUrl: string | null;
      author: null;
      tags: null;
      footnotes: null;
      issue: null;
      translation: {
        _id: string;
        title: string;
        slug: Slug;
        language: "en" | "hu";
      } | null;
      content: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h2"
              | "h3"
              | "h4"
              | "normal-center"
              | "normal-right"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs: Array<
              | {
                  reference:
                    | {
                        _type: "article";
                        _id: string;
                        title: string;
                        slug: Slug;
                        issueNumber: null;
                        issueType: null;
                        publishedAt: null;
                      }
                    | {
                        _type: "issue";
                        _id: string;
                        title: string;
                        slug: null;
                        issueNumber: number;
                        issueType: "regular" | "special";
                        publishedAt: string;
                      }
                    | {
                        _type: "standaloneBook";
                        _id: string;
                        title: string;
                        slug: Slug;
                        issueNumber: null;
                        issueType: null;
                        publishedAt: null;
                      };
                  _type: "internalLink";
                  _key: string;
                }
              | {
                  href: string;
                  _type: "link";
                  _key: string;
                }
            > | null;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            hasHeader?: boolean;
            title?: string;
            table?: Table;
            _type: "customTable";
            _key: string;
            markDefs: null;
          }
        | {
            style?: "dashed" | "default";
            _type: "divider";
            _key: string;
            markDefs: null;
          }
        | {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            caption?: string;
            alt?: string;
            _type: "image";
            _key: string;
            markDefs: null;
          }
      >;
    }
  | null;

// Source: ../web/src/lib/queries.ts
// Variable: GET_SEARCH_FILTERS_QUERY
// Query: {    "authors": *[_type == "author"] | order(name asc){        _id,        name    },    "issues": *[_type == "issue"] | order(publishedAt desc, issueNumber desc){        _id,        title,        issueNumber,        issueType,        publishedAt    },    "tags": *[_type == "tag"] | order(title asc){        _id,        title,        slug,        "articleCount": count(*[_type == "article" && references(^._id)])    }}
export type GET_SEARCH_FILTERS_QUERY_RESULT = {
  authors: Array<{
    _id: string;
    name: string;
  }>;
  issues: Array<{
    _id: string;
    title: string;
    issueNumber: number;
    issueType: "regular" | "special";
    publishedAt: string;
  }>;
  tags: Array<{
    _id: string;
    title: string;
    slug: Slug;
    articleCount: number;
  }>;
};

// Source: ../web/src/lib/queries.ts
// Variable: SEARCH_ARTICLES_QUERY
// Query: *[    _type == "article"    && ($authorId == "" || author._ref == $authorId)    && ($issueId == "" || issue._ref == $issueId)    && (count($tagSlugs) == 0 || count((tags[]->slug.current)[@ in $tagSlugs]) > 0)] | order(publishedAt desc, _createdAt desc) {    _id,    title,    subtitle,    scripture,    slug,    language,    publishedAt,    author->{        _id,        name    },    tags[]->{        _id,        title,        slug    },    "issue": issue->{        _id,        title,        issueNumber,        issueType,        publishedAt    },    "plainContent": pt::text(content)}
export type SEARCH_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  subtitle: string | null;
  scripture: string | null;
  slug: Slug;
  language: "en" | "hu";
  publishedAt: null;
  author: {
    _id: string;
    name: string;
  } | null;
  tags: Array<{
    _id: string;
    title: string;
    slug: Slug;
  }> | null;
  issue: {
    _id: string;
    title: string;
    issueNumber: number;
    issueType: "regular" | "special";
    publishedAt: string;
  } | null;
  plainContent: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  headerTitle,\n  headerSubtitle,\n  headerSearchButtonLabel,\n  headerMenu[]{\n    label,\n    url\n  },\n  footerCopyright,\n  footerQuoteText,\n  footerQuoteSource,\n  footerMenu1Title,\n  footerMenu1[]{\n    label,\n    url\n  },\n  footerMenu2Title,\n  footerMenu2[]{\n    label,\n    url\n  }\n}': GET_SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n  heroImage {\n    asset->{\n      _id,\n      url\n    },\n    alt\n  },\n  heroTitle,\n  heroSubtitle,\n  latestIssueTitle,\n  welcomeTitle,\n  welcomeContent[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          _id,\n          title,\n          slug,\n          issueNumber,\n          issueType,\n          publishedAt\n        }\n      }\n    }\n  },\n  popularTagsTitle\n}': GET_HOME_PAGE_QUERY_RESULT;
    '*[_type == "magazinePage"][0]{\n  title,\n  description,\n  carouselSelectLabel,\n  articlesTabLabel,\n  audiobookTabLabel,\n  audiobookUnavailableLabel,\n  downloadPdfButtonLabel,\n  emptyTitle,\n  emptyDescription\n}': GET_MAGAZINE_PAGE_QUERY_RESULT;
    '*[_type == "aboutPage"][0]{\n  _id,\n  title,\n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          _id,\n          title,\n          slug,\n          issueNumber,\n          issueType,\n          publishedAt\n        }\n      }\n    }\n  }\n}': GET_ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "contactPage"][0]{\n  _id,\n  title,\n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          _id,\n          title,\n          slug,\n          issueNumber,\n          issueType,\n          publishedAt\n        }\n      }\n    }\n  },\n  recipientEmail,\n  formNameLabel,\n  formNamePlaceholder,\n  formEmailLabel,\n  formEmailPlaceholder,\n  formMessageLabel,\n  formMessagePlaceholder,\n  formSubmitButtonLabel,\n  formSuccessTitle,\n  formSuccessMessage,\n  formSuccessButtonLabel,\n  formErrorMessage\n}': GET_CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "englishArticlesPage"][0]{\n  title,\n  description,\n  readButtonLabel,\n  emptyTitle,\n  emptyDescription\n}': GET_ENGLISH_ARTICLES_PAGE_QUERY_RESULT;
    '*[_type == "privacyPage"][0]{\n  _id,\n  title,\n  slug,\n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        "reference": reference->{\n          _type,\n          _id,\n          title,\n          slug,\n          issueNumber,\n          issueType,\n          publishedAt\n        }\n      }\n    }\n  }\n}': GET_PRIVACY_PAGE_QUERY_RESULT;
    '*[_type == "article" && language == "en"] | order(_createdAt desc){\n  _id,\n  title,\n  subtitle,\n  scripture,\n  slug,\n  language,\n  author->{\n    _id,\n    name\n  },\n  tags[]->{\n    _id,\n    title,\n    slug\n  },\n  "issue": issue->{\n    _id,\n    title,\n    issueNumber,\n    issueType,\n    publishedAt\n  }\n}': GET_ENGLISH_ARTICLES_QUERY_RESULT;
    '*[_type == "searchPage"][0]{\n  title,\n  description,\n  queryLabel,\n  queryPlaceholder,\n  authorLabel,\n  authorAllOption,\n  issueLabel,\n  issueAllOption,\n  tagLabel,\n  tagSearchPlaceholder,\n  resetButtonLabel,\n  resultsHeading,\n  readButtonLabel,\n  noResultsTitle,\n  noResultsDescription\n}': GET_SEARCH_PAGE_QUERY_RESULT;
    '*[_type == "issue"] | order(publishedAt desc, issueNumber desc)[0]{\n    _id,\n    title,\n    issueNumber,\n    issueType,\n    publishedAt,\n    youtubeUrl,\n    "pdfUrl": pdfFile.asset->url,\n    coverImage {\n        asset->{\n            _id,\n            url\n        },\n        alt\n    },\n    "articles": *[_type == "article" && issue._ref == ^._id] | order(order asc) {\n        _id,\n        title,\n        subtitle,\n        scripture,\n        slug,\n        language,\n        author->{\n            _id,\n            name\n        },\n        tags[]->{\n            _id,\n            title,\n            slug\n        }\n    }\n}': GET_NEWEST_ISSUE_QUERY_RESULT;
    '*[_type == "issue"] | order(publishedAt desc, issueNumber desc) {\n    _id,\n    title,\n    issueNumber,\n    issueType,\n    publishedAt,\n    youtubeUrl,\n    "pdfUrl": pdfFile.asset->url,\n    coverImage {\n        asset->{\n            _id,\n            url\n        },\n        alt\n    },\n    "articleCount": count(*[_type == "article" && issue._ref == ^._id]),\n    "articles": *[_type == "article" && issue._ref == ^._id] | order(order asc) {\n        _id,\n        title,\n        subtitle,\n        scripture,\n        slug,\n        language,\n        author->{\n            _id,\n            name\n        },\n        tags[]->{\n            _id,\n            title,\n            slug\n        }\n    }\n}': GET_ALL_ISSUES_QUERY_RESULT;
    '*[_type in ["article", "standaloneBook"] && slug.current == $slug][0]{\n    _type,\n    _id,\n    title,\n    subtitle,\n    scripture,\n    slug,\n    language,\n    coverImage {\n        asset->{\n            _id,\n            url\n        },\n        alt\n    },\n    youtubeUrl,\n    "pdfUrl": pdfFile.asset->url,\n    author->{\n        _id,\n        name\n    },\n    tags[]->{\n        _id,\n        title,\n        slug\n    },\n    footnotes[]{\n        number,\n        text,\n        anchorId\n    },\n    "issue": issue->{\n        _id,\n        title,\n        issueNumber,\n        issueType,\n        publishedAt,\n        "articles": *[_type == "article" && issue._ref == ^._id] | order(order asc) {\n            _id,\n            title,\n            slug\n        }\n    },\n    "translation": coalesce(\n        translation->{\n            _id,\n            title,\n            slug,\n            language\n        },\n        *[_type == "article" && translation._ref == ^._id][0]{\n            _id,\n            title,\n            slug,\n            language\n        }\n    ),\n    content[]{\n        ...,\n        markDefs[]{\n            ...,\n            _type == "internalLink" => {\n                "reference": reference->{\n                    _type,\n                    _id,\n                    title,\n                    slug,\n                    issueNumber,\n                    issueType,\n                    publishedAt\n                }\n            }\n        }\n    }\n}': GET_DOCUMENT_BY_SLUG_QUERY_RESULT;
    '{\n    "authors": *[_type == "author"] | order(name asc){\n        _id,\n        name\n    },\n    "issues": *[_type == "issue"] | order(publishedAt desc, issueNumber desc){\n        _id,\n        title,\n        issueNumber,\n        issueType,\n        publishedAt\n    },\n    "tags": *[_type == "tag"] | order(title asc){\n        _id,\n        title,\n        slug,\n        "articleCount": count(*[_type == "article" && references(^._id)])\n    }\n}': GET_SEARCH_FILTERS_QUERY_RESULT;
    '*[\n    _type == "article"\n    && ($authorId == "" || author._ref == $authorId)\n    && ($issueId == "" || issue._ref == $issueId)\n    && (count($tagSlugs) == 0 || count((tags[]->slug.current)[@ in $tagSlugs]) > 0)\n] | order(publishedAt desc, _createdAt desc) {\n    _id,\n    title,\n    subtitle,\n    scripture,\n    slug,\n    language,\n    publishedAt,\n    author->{\n        _id,\n        name\n    },\n    tags[]->{\n        _id,\n        title,\n        slug\n    },\n    "issue": issue->{\n        _id,\n        title,\n        issueNumber,\n        issueType,\n        publishedAt\n    },\n    "plainContent": pt::text(content)\n}': SEARCH_ARTICLES_QUERY_RESULT;
  }
}
